// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejuvgifqgxihsipdcalt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdXZnaWZxZ3hpaHNpcGRjYWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDU5MTUsImV4cCI6MjA2OTg4MTkxNX0.x5An-qfIhQaiF9zsgZKLWblkbg0Phdh5Z6dsZ53foQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});